### ISSUE TITLE
[BUG/Help] <title>测试代码生成时出现死循环

### ISSUE THREAD

**Issue by cssword** [THUDM/ChatGLM2-6B#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

想看看GLM2的代码生成能力，随便问了一个问题，结果疯狂生成代码，不断重复，一直也没有停止的迹象，直到token用完为止。
参考：

`
用户：用uniapp写一个用户登录的界面，支持密码登录和验证码登录

ChatGLM：以下是一个使用 UniApp 编写的用户登录界面，支持密码登录和验证码登录：
```css
<template>
  <view class="container">
    <view class="form-container">
      <form>
        <view class="form-group">
          <label for="username">用户名：</label>
          <input type="text" id="username" name="username" required>
        </view>
        <view class="form-group">
          <label for="password">密码：</label>
          <input type="password" id="password" name="password" required>
        </view>
        <view class="form-group">
          <label for="code">验证码：</label>
          <input type="text" id="code" name="code" required>
        </view>
        <view class="form-group">
          <div class="check-input" @click="checkCode">
            {{code}}
          </div>
          <button type="button" @click="submitForm">登录</button>
        </view>
      </form>
    </view>
    <view class="login-container">
      <div class="message" @click="showMessage">
        <span class="close" @click="closeMessage">&times;</span>
        <p>欢迎 {{username}} 登录</p>
      </div>
      <div class="loading" @click="isLoading">
        <span class="close" @click="closeLoading">&times;</span>
        <div class="spinner" @click="startSpinner">
          <div class="spinner-border" />
        </div>
      </div>
    </view>
  </view>
</template>

<script>
export default {
  data() {
    return {
      username: '',
      password: '',
      code: '',
      isLoading: true,
      loading: false,
      message: '',
      codeInput: '',
    };
  },
  methods: {
    checkCode() {
      const code = this.code;
      if (code === '0') {
        this.isLoading = false;
        this.message = '验证码正确';
        this.submitForm();
      } else {
        this.isLoading = false;
        this.message = '';
      }
    },
    submitForm() {
      console.log('开始提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
    startSpinner() {
      this.loading = true;
      this.spinner = this.spinner || this.createElement('div');
      this.spinner.classList.add('spinner-border', 'pinner-线条');
      setTimeout(() => {
        this.spinner.innerHTML = '<div class="spinner-border" style="display: inline-block; width: 6px; height: 6px;border-width: 0;border-right-width: 0;border-bottom-width: 0;border-left-width: 0;animation: spinner-border 1 100 linear infinite;transform-origin: 0 16px 0;transform-scale: 0 0.8 0.9;will-change: transform-origin, transform-scale">
          <div class="spinner-border" style="width: 6px; height: 6px;border-width: 0;border-right-width: 0;border-bottom-width: 0;border-left-width: 0"></div>
        </div>';
        this.spinner.style.display = 'none';
        this.isLoading = false;
        setTimeout(() => {
          this.submitForm();
        }, 5000);
      }, 5000);
    },
    submitForm() {
      console.log('提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
    closeLoading() {
      this.loading = false;
    },
    closeMessage() {
      this.message = '';
    },
    isLoading(isLoading) {
      return isLoading;
    },
    startSpinner() {
      const loading = this.isLoading(true);
      const spinner = this.isLoading(false)? this.spinner : this.createElement('div');
      spinner.setAttribute('class', 'pinner-border');
      spinner.setAttribute('style', `width: ${loading.width}px;height: ${loading.height}px;border-width: ${loading.borderWidth}px;border-right-width: ${loading.borderRightWidth}px;border-bottom-width: ${loading.borderBottomWidth}px;border-left-width: ${loading.borderLeftWidth}px;animation: spinner-border 1 100 linear ${isLoading? 'nfinite' : 'low'};`);
      loading.appendChild(spinner);
    },
  },
  methods: {
    checkCode() {
      const code = this.code;
      if (code === '0') {
        this.isLoading = false;
        this.message = '验证码正确';
        this.submitForm();
      } else {
        this.isLoading = false;
        this.message = '';
      }
    },
    submitForm() {
      console.log('开始提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
  },
  computed: {
    isLoading() {
      return this.loading || this.isLoading(false);
    },
  },
  watch: {
    isLoading() {
      if (!this.isLoading) {
        this.startSpinner();
      }
    },
  },
  mounted() {
    this.startSpinner();
  },
  methods: {
    startSpinner() {
      this.spinner.style.display = 'block';
      this.isLoading = true;
      setTimeout(() => {
        this.isLoading = false;
        this.submitForm();
      }, 5000);
    },
    submitForm() {
      console.log('提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
  },
  components: {
    createElement(name, attrs) {
      return document.createElement(name, attrs);
    },
  },
  style: `
   .spinner-border {
      width: ${this.loading.width}px;
      height: ${this.loading.height}px;
      border-width: ${this.loading.borderWidth}px;
      border-right-width: ${this.loading.borderRightWidth}px;
      border-bottom-width: ${this.loading.borderBottomWidth}px;
      border-left-width: ${this.loading.borderLeftWidth}px;
      animation: spinner-border 1 100 linear infinite;
      transform-origin: 0 16px 0;
      transform-scale: 0 0.8 0.9;
      will-change: transform-origin, transform-scale;
    }

   .spinner-border.spinner-border-fa {
      width: 6px;
      height: 6px;
      border-width: 0;
      border-right-width: 0;
      border-bottom-width: 0;
      border-left-width: 0;
      animation: spinner-border 1 100 linear infinite;
      transform-origin: 0 16px 0;
      transform-scale: 0 0.8 0.9;
      will-change: transform-origin, transform-scale;
    }

    @keyframes spinner-border {
      0% {
        transform-origin: 0 16px 0;
        transform-scale: 0 0.8 0.9;
      }
      100% {
        transform-origin: 360px 16px 0;
        transform-scale: 0 0.8 0.9;
      }
    }

    @keyframes spinner-border-fa {
      0% {
        transform-origin: 0 16px 0;
        transform-scale: 0 0.8 0.9;
      }
      100% {
        transform-origin: 360px 16px 0;
        transform-scale: 0 0.8 0.9;
      }
    }
  `,
},
};

export default {
  data() {
    return {
      username: '',
      password: '',
      code: '',
      isLoading: true,
    };
  },
  methods: {
    submitForm() {
      console.log('提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
  },
  computed: {
    isLoading() {
      return this.loading || this.isLoading(false);
    },
  },
  watch: {
    isLoading() {
      if (!this.isLoading) {
        this.startSpinner();
      }
    },
  },
  mounted() {
    this.startSpinner();
  },
  methods: {
    startSpinner() {
      this.spinner = this.isLoading(false)? this.spinner : this.createElement('div');
      this.spinner.classList.add('spinner-border');
      this.spinner.style.display = 'none';
      setTimeout(() => {
        this.isLoading = false;
        this.submitForm();
      }, 5000);
    },
    submitForm() {
      console.log('开始提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
  },
  components: {
    createElement(name, attrs) {
      return document.createElement(name, attrs);
    },
  },
  style: `
   .spinner-border.spinner-border-fa {
      width: 6px;
      height: 6px;
      border-width: 0;
      border-right-width: 0;
      border-bottom-width: 0;
      border-left-width: 0;
      animation: spinner-border 1 100 linear infinite;
      transform-origin: 0 16px 0;
      transform-scale: 0 0.8 0.9;
      will-change: transform-origin, transform-scale;
    }

   .spinner-border.spinner-border-fa.spinner-border-fa-fa {
      width: 6px;
      height: 6px;
      border-width: 0;
      border-right-width: 0;
      border-bottom-width: 0;
      border-left-width: 0;
      transform-origin: 0 16px 0;
      transform-scale: 0 0.8 0.9;
      will-change: transform-origin, transform-scale;
    }

    @keyframes spinner-border {
      0% {
        transform-origin: 0 16px 0;
        transform-scale: 0 0.8 0.9;
      }
      100% {
        transform-origin: 360px 16px 0;
        transform-scale: 0 0.8 0.9;
      }
    }

    @keyframes spinner-border-fa {
      0% {
        transform-origin: 0 16px 0;
        transform-scale: 0 0.8 0.9;
      }
      100% {
        transform-origin: 360px 16px 0;
        transform-scale: 0 0.8 0.9;
      }
    }
  `,
},
};

export default {
  data() {
    return {
      username: '',
      password: '',
      code: '',
      isLoading: true,
    };
  },
  methods: {
    submitForm() {
      console.log('开始提交表单...');
      this.loading = true;
      try {
        if (this.username === '' || this.password === '') {
          this.message = '请填写用户名和密码';
          return;
        }
        if (this.code === '') {
          this.message = '请选择验证码';
          return;
        }
        this.loading = false;
        this.isLoading = false;
        const xhr = new XMLHttpRequest();
        xhr.open('https://example.com/api/login', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
      } catch (e) {
        this.message = '登录失败';
        return;
      }
    },
  },
  computed: {
```

用户：

`

### Expected Behavior

不出现死循环，能够去除重复内容

### Steps To Reproduce

1. ChatGLM2-6B最新版github下载
2. 模型chatglm2-6b-int4
3. python cli_demo.py
4. 用户提问： 请用uniapp生成一个登录页面，包含密码登录和验证码登录

### Environment

```markdown
- OS: Windows11
- Python: 3.10.9
- Transformers: 4.30.2
- PyTorch: 2.0.0+cuda118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```
